# coding: utf-8

"""
    Traffic data concentrator - OpenAPI 3.0

    This is a development Swagger-supported server based on the OpenAPI 3.0 specification. You can find out more about Swagger at  [https://swagger.io](https://swagger.io).  # noqa: E501

    OpenAPI spec version: 0.9.4
    Contact: d3e@fd.cvut.cz
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.scalalast_data_detectors import ScalalastDataDetectors  # noqa: E501
from swagger_client.rest import ApiException


class TestScalalastDataDetectors(unittest.TestCase):
    """ScalalastDataDetectors unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testScalalastDataDetectors(self):
        """Test ScalalastDataDetectors"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.scalalast_data_detectors.ScalalastDataDetectors()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
