# coding: utf-8

"""
    Traffic data concentrator - OpenAPI 3.0

    This is a development Swagger-supported server based on the OpenAPI 3.0 specification. You can find out more about Swagger at  [https://swagger.io](https://swagger.io).  # noqa: E501

    OpenAPI spec version: 0.9.4
    Contact: d3e@fd.cvut.cz
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.camea_api import CameaApi  # noqa: E501
from swagger_client.rest import ApiException


class TestCameaApi(unittest.TestCase):
    """CameaApi unit test stubs"""

    def setUp(self):
        self.api = CameaApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_camea_get_endpoints(self):
        """Test case for camea_get_endpoints

        Retrieve detector ids  # noqa: E501
        """
        pass

    def test_camea_get_last_data(self):
        """Test case for camea_get_last_data

        Retrieve last data from CAMEA detectors  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
