# coding: utf-8

"""
    Traffic data concentrator - OpenAPI 3.0

    This is a development Swagger-supported server based on the OpenAPI 3.0 specification. You can find out more about Swagger at  [https://swagger.io](https://swagger.io).  # noqa: E501

    OpenAPI spec version: 0.9.4
    Contact: d3e@fd.cvut.cz
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.golemio_api import GolemioApi  # noqa: E501
from swagger_client.rest import ApiException


class TestGolemioApi(unittest.TestCase):
    """GolemioApi unit test stubs"""

    def setUp(self):
        self.api = GolemioApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_golemio_get_last_data(self):
        """Test case for golemio_get_last_data

        Get last data uploaded from the Golemio platform  # noqa: E501
        """
        pass

    def test_golemio_get_lines(self):
        """Test case for golemio_get_lines

        Retrieve list of public transport lines covered by golemio  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
