# coding: utf-8

"""
    Traffic data concentrator - OpenAPI 3.0

    This is a development Swagger-supported server based on the OpenAPI 3.0 specification. You can find out more about Swagger at  [https://swagger.io](https://swagger.io).  # noqa: E501

    OpenAPI spec version: 0.9.4
    Contact: d3e@fd.cvut.cz
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class GolemiolastDataVehicles(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'vehicleno': 'str',
        'latitude': 'float',
        'longitude': 'float',
        'time': 'str'
    }

    attribute_map = {
        'vehicleno': 'vehicleno',
        'latitude': 'latitude',
        'longitude': 'longitude',
        'time': 'time'
    }

    def __init__(self, vehicleno=None, latitude=None, longitude=None, time=None):  # noqa: E501
        """GolemiolastDataVehicles - a model defined in Swagger"""  # noqa: E501
        self._vehicleno = None
        self._latitude = None
        self._longitude = None
        self._time = None
        self.discriminator = None
        if vehicleno is not None:
            self.vehicleno = vehicleno
        if latitude is not None:
            self.latitude = latitude
        if longitude is not None:
            self.longitude = longitude
        if time is not None:
            self.time = time

    @property
    def vehicleno(self):
        """Gets the vehicleno of this GolemiolastDataVehicles.  # noqa: E501

        Unique identifier of the PT vehicle (chasis number, registration number, license plate)  # noqa: E501

        :return: The vehicleno of this GolemiolastDataVehicles.  # noqa: E501
        :rtype: str
        """
        return self._vehicleno

    @vehicleno.setter
    def vehicleno(self, vehicleno):
        """Sets the vehicleno of this GolemiolastDataVehicles.

        Unique identifier of the PT vehicle (chasis number, registration number, license plate)  # noqa: E501

        :param vehicleno: The vehicleno of this GolemiolastDataVehicles.  # noqa: E501
        :type: str
        """

        self._vehicleno = vehicleno

    @property
    def latitude(self):
        """Gets the latitude of this GolemiolastDataVehicles.  # noqa: E501

        Numeric WGS84 latitude of the vehicle  # noqa: E501

        :return: The latitude of this GolemiolastDataVehicles.  # noqa: E501
        :rtype: float
        """
        return self._latitude

    @latitude.setter
    def latitude(self, latitude):
        """Sets the latitude of this GolemiolastDataVehicles.

        Numeric WGS84 latitude of the vehicle  # noqa: E501

        :param latitude: The latitude of this GolemiolastDataVehicles.  # noqa: E501
        :type: float
        """

        self._latitude = latitude

    @property
    def longitude(self):
        """Gets the longitude of this GolemiolastDataVehicles.  # noqa: E501

        Numeric WGS84 longitude of the vehicle  # noqa: E501

        :return: The longitude of this GolemiolastDataVehicles.  # noqa: E501
        :rtype: float
        """
        return self._longitude

    @longitude.setter
    def longitude(self, longitude):
        """Sets the longitude of this GolemiolastDataVehicles.

        Numeric WGS84 longitude of the vehicle  # noqa: E501

        :param longitude: The longitude of this GolemiolastDataVehicles.  # noqa: E501
        :type: float
        """

        self._longitude = longitude

    @property
    def time(self):
        """Gets the time of this GolemiolastDataVehicles.  # noqa: E501

        Timestamp of the position report.  # noqa: E501

        :return: The time of this GolemiolastDataVehicles.  # noqa: E501
        :rtype: str
        """
        return self._time

    @time.setter
    def time(self, time):
        """Sets the time of this GolemiolastDataVehicles.

        Timestamp of the position report.  # noqa: E501

        :param time: The time of this GolemiolastDataVehicles.  # noqa: E501
        :type: str
        """

        self._time = time

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GolemiolastDataVehicles, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GolemiolastDataVehicles):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
