# coding: utf-8

"""
    Traffic data concentrator - OpenAPI 3.0

    This is a development Swagger-supported server based on the OpenAPI 3.0 specification. You can find out more about Swagger at  [https://swagger.io](https://swagger.io).  # noqa: E501

    OpenAPI spec version: 0.9.4
    Contact: d3e@fd.cvut.cz
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class InlineResponse2001Intersection(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'detector': 'list[InlineResponse2001Detector]'
    }

    attribute_map = {
        'id': 'id',
        'detector': 'detector'
    }

    def __init__(self, id=None, detector=None):  # noqa: E501
        """InlineResponse2001Intersection - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._detector = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if detector is not None:
            self.detector = detector

    @property
    def id(self):
        """Gets the id of this InlineResponse2001Intersection.  # noqa: E501


        :return: The id of this InlineResponse2001Intersection.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this InlineResponse2001Intersection.


        :param id: The id of this InlineResponse2001Intersection.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def detector(self):
        """Gets the detector of this InlineResponse2001Intersection.  # noqa: E501


        :return: The detector of this InlineResponse2001Intersection.  # noqa: E501
        :rtype: list[InlineResponse2001Detector]
        """
        return self._detector

    @detector.setter
    def detector(self, detector):
        """Sets the detector of this InlineResponse2001Intersection.


        :param detector: The detector of this InlineResponse2001Intersection.  # noqa: E501
        :type: list[InlineResponse2001Detector]
        """

        self._detector = detector

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse2001Intersection, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse2001Intersection):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
