# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InlineResponse2003(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, detector_id: str=None):  # noqa: E501
        """InlineResponse2003 - a model defined in Swagger

        :param detector_id: The detector_id of this InlineResponse2003.  # noqa: E501
        :type detector_id: str
        """
        self.swagger_types = {
            'detector_id': str
        }

        self.attribute_map = {
            'detector_id': 'detector_id'
        }
        self._detector_id = detector_id

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2003':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_3 of this InlineResponse2003.  # noqa: E501
        :rtype: InlineResponse2003
        """
        return util.deserialize_model(dikt, cls)

    @property
    def detector_id(self) -> str:
        """Gets the detector_id of this InlineResponse2003.


        :return: The detector_id of this InlineResponse2003.
        :rtype: str
        """
        return self._detector_id

    @detector_id.setter
    def detector_id(self, detector_id: str):
        """Sets the detector_id of this InlineResponse2003.


        :param detector_id: The detector_id of this InlineResponse2003.
        :type detector_id: str
        """
        if detector_id is None:
            raise ValueError("Invalid value for `detector_id`, must not be `None`")  # noqa: E501

        self._detector_id = detector_id
