# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.inline_response2001_intersection import InlineResponse2001Intersection  # noqa: F401,E501
from swagger_server import util


class InlineResponse2001(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, intersection: List[InlineResponse2001Intersection]=None):  # noqa: E501
        """InlineResponse2001 - a model defined in Swagger

        :param intersection: The intersection of this InlineResponse2001.  # noqa: E501
        :type intersection: List[InlineResponse2001Intersection]
        """
        self.swagger_types = {
            'intersection': List[InlineResponse2001Intersection]
        }

        self.attribute_map = {
            'intersection': 'intersection'
        }
        self._intersection = intersection

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2001':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_1 of this InlineResponse2001.  # noqa: E501
        :rtype: InlineResponse2001
        """
        return util.deserialize_model(dikt, cls)

    @property
    def intersection(self) -> List[InlineResponse2001Intersection]:
        """Gets the intersection of this InlineResponse2001.


        :return: The intersection of this InlineResponse2001.
        :rtype: List[InlineResponse2001Intersection]
        """
        return self._intersection

    @intersection.setter
    def intersection(self, intersection: List[InlineResponse2001Intersection]):
        """Sets the intersection of this InlineResponse2001.


        :param intersection: The intersection of this InlineResponse2001.
        :type intersection: List[InlineResponse2001Intersection]
        """

        self._intersection = intersection
